name: Framework

on:
  pull_request:
    branches:
      - main
      - stolostron
      - release-[0-9]+.[0-9]+

jobs:
  fw-kind-tests:
    name: KinD
    uses: JustinKuli/governance-policy-framework/.github/workflows/kind.yml@ecbd83b884d091d5a40b3724d034936003fee7a6
