name: Framework

on:
  pull_request:
    branches:
      - main
      - stolostron
      - release-[0-9]+.[0-9]+

jobs:
  fw-kind-tests:
    name: KinD
    uses: JustinKuli/governance-policy-framework/.github/workflows/kind.yml@93a59601674bc6a5e929a3ee76ee2c2316de4d06
